---
title: "CS7641 Machine Learning First Assignment "
author: "T. Ruzmetov"
date: "September 20, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
```

\center                  \center

# Introduction

Purpose of this assignmet is to investigate and compare the performance of five different machine
learning techniques such as K-Neirest Naighbour, Desicion Trees, Boosted Desision Trees, Support Vector
Machines and Artificial Neural Networks when applied to two distinct classification problems(distinct datasets).
In order to fullfil the requirement, "Lending Club Dataset" from Kaggle and Adult Dataset from UCI machine
leraning repository is utilized. 



## Lending Club Dataset

Lending Club is the world’s largest online marketplace connecting borrowers and investors. Provided dataset
contain complete loan data for all loans issued through 2007 to 2015, including the current loan status(Current,
Late, Fully Paid, etc.). In this problem, we are suppose to predicte if customer is goint to pay or default on
their loan based on provided set of features with labels. Instances with "Current" loan status are discarded to
make it simple binary classification problem with two labels(defaulted=0, paid=1). After cleaning and feature
extraction, the dataset contains 15 features and 285373 samples. Only 10% of this data is used for modelling in
order to reduce training time. 


## Adult Dataset

The adult data set has over 22000 instances and 14 features of mostly cate-
gorical variables. I did some preprocessing of the original data by discarding
couple of repeated attributes and clean the categorical values by giving good
names. We see from the table 1 that the binary classes are imbalanced. So, in
addition to Accuracy metric, ROC metric is also needed for this data set
when we compare and contrast different algorithms.






## K-Neirest Naighbour 



## Desicion Tree Algorithm with Prunning




## Gradient Boosting




## Neural Networks




## Support Vector Machines




## Conclusion



